Day4Challenge/TruckSmartWeb/Controllers/DriverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TruckSmartWeb.Models;

namespace TruckSmartWeb.Controllers
{
    
    public class DriverController : Controller
    {
        // GET: Driver
        TruckSmartContext context = new TruckSmartContext();
        public ActionResult Index()
        {
            var driverData = new DriverData { MyShipments = context.GetMyShipments(), OpenShipments = context.GetOpenShipments()};
            return View(driverData);
        }
        public ActionResult DisplayShipment(Guid id)
        {
            
            return View(context.GetShipment(id));
        }

        public ActionResult ReserveShipment(Guid id)
        {
            return View(context.GetShipment(id));
        }
        [HttpPost]
        public ActionResult ReserveShipment(Guid id, bool Reserve)
        {
            context.ReserveShipment(id);
            return RedirectToAction("Index");
        }
        public ActionResult ReleaseShipment(Guid id)
        {
            return View(context.GetShipment(id));
        }
        [HttpPost]
        public ActionResult ReleaseShipment(Guid id, bool Release)
        {
            context.ReleaseShipment(id);
            return RedirectToAction("Index");
        }
        public ActionResult Info()
        {
            return View();
        }
    }

    public class DriverData
    {
        public List<Shipment> MyShipments { get; set; }
        public List<Shipment> OpenShipments { get; set; }
    }

}

Day4Challenge/TruckSmartWeb/Controllers/ServiceProviderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TruckSmartWeb.Models;

namespace TruckSmartWeb.Controllers
{
    public class ServiceProviderController : Controller
    {
        // GET: ServiceProvider
        private TruckSmartContext context = new TruckSmartContext();
        public ActionResult Index()
        {
            return View(context.GetProviders());
        }

        public ActionResult GetProvider(double latitude, double longitude)
        {
            return View(context.GetNearestProvider(latitude, longitude));
        }
    }
}

Day4Challenge/TruckSmartWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-fixed-top navbar-right">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Truck Smart", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse navbar-right">
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Drivers", "Index", "Driver", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Emergencies", "Index", "ServiceProvider", new { area = "" }, null)</li>
                    
                </ul>
            </div>
        </div>

    </div>
    <div class="container body-content">
        @if (System.Configuration.ConfigurationManager.AppSettings["production"].ToLower() == "false")
        {
            <h2 class="warning">You are working in a development or test environment</h2>
        }
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Wunhill TruckSmart&trade;</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>